name: CI Workflow
on:
  push:
    branches:
    - main

jobs:
  build-containers:
    name: Build Containers
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [windows-2022]
        include:
        - os: windows-2022
          base: nanoserver-ltsc2022
          file: Dockerfile.windows
          artifact: gmsv_MongoDb_win64.dll
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      # https://github.com/docker/build-push-action/issues/18
      # uses: docker/build-push-action@v2
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: gmod-mongodb/build
        dockerfile: ${{ matrix.file }}
        tags: ${{ matrix.os }}
        pushImage: false

    - name: Extract artifact
      run:
        CID=$(docker create ${ matrix.os }) && \
        docker cp ${CID}:/app/build ./ && \
        docker rm ${CID}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: build/bin/release/${{matrix.artifact}}
