name: CI Workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  build-containers:
    name: Build Containers
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [windows-2022, ubuntu-22.04]
        include:
        - os: windows-2022
          file: Dockerfile.windows
          artifact-path: build/bin/release
          artifact: gmsv_mongodb_win64.dll
        - os: ubuntu-22.04
          file: Dockerfile.linux
          artifact-path: build/projects/MongoDb
          artifact: gmsv_mongodb_linux64.dll
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Build
      shell: bash
      run: >
        docker build -f ${{ matrix.file }} . -t build-image &&
        docker cp $(docker create build-image):/app/build .

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.artifact}}
        path: ${{matrix.artifact-path}}/${{matrix.artifact}}
